### PR TITLE
Storage type improvements

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?

PatternFly switch component:
- added attribute to disable the component

Storage Type switch on Get Started tab:
- correctly initialize the toggle with the default storage type
- disable the toggle in case when the only storage type is available
Screenshot_20200901_131000

Storage Type select on Custom Workspace tab:
- correctly initialize storage type select with the default storage type value
- disable the select in case when the only storage type is available
Screenshot_20200901_131506

- fixes updating the devfile editor on selecting the storage type

### What issues does this PR fix or reference?

fixes https://github.com/eclipse/che/issues/17725

### CODE REVIEW

**Review by sleshchenko — COMMENTED** [review]
At this point there is still bug exists: workspace is created by get started page while ephemeral mode is enabled by default. But no more bugs found.

**Comment by akurinnoy** [comment]
@sleshchenko I hope that bug's fixed now, please test one more time

**Comment by ibuziuk** [comment]
thanks folks, any chance we can backport it to 7.18.1 also?

**Comment by akurinnoy** [comment]
@ibuziuk I'll cherry-pick changes to that branch as well

**Pull request merged**
