### PR TITLE
Remove duplicating product name from version title

### PR DESCRIPTION
**Pull request by sleshchenko**
### What does this PR do?
Removes duplicating product name from version title.

Screenshot_20210322_181555

### What issues does this PR fix or reference?
It seems to be what Parvathy suggested in https://github.com/eclipse/che/issues/18567#issuecomment-742640132
and it's what Nick suggests in https://issues.redhat.com/browse/CRW-1676

### CODE REVIEW

**Comment by nickboldt** [comment]
+1, love it.

**Review by nickboldt — APPROVED** [review]

**Review by akurinnoy — APPROVED** [review]
Please clean up the variable declaration as it's no longer in use:

https://github.com/eclipse/che-dashboard/pull/192/files#diff-e0c64a24d34b66f29b8a8c38a7d643d1f081988030ea96e4e7abe47fea60f878R43

**Comment by akurinnoy** [comment]
@sleshchenko There is one failed test (which I haven't noticed before approving) that you can easily fix, or just ping me if any help is needed.

**Review by JPinkney — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
[dashboard-next-ci-test]

**Comment by dmytro-ndp** [comment]
[dashboard-next-ci-test]

**Comment by dmytro-ndp** [comment]
[dashboard-next-ci-test]

**Comment by dmytro-ndp** [comment]
[dashboard-next-ci-test]

**Pull request merged**
