### PR TITLE
Apply the preferred type for creating a new workspace from a sample flow

### PR DESCRIPTION
**Pull request by olexii4**
Signed-off-by: Oleksii Orel <oorel@redhat.com>

### What does this PR do?
Apply the preferred type for creating a new workspace from a sample flow.

### What issues does this PR fix or reference?
fixes get started case in https://github.com/eclipse/che/issues/19069
fixes https://github.com/eclipse/che/issues/19250

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
[dashboard-next-ci-test]

**Comment by olexii4** [comment]
[dashboard-next-ci-test]

**Review by sleshchenko — APPROVED** [review]
Tested and get started works as expected to me

**Review by JPinkney — APPROVED** [review]
Just tested with the latest changes and everything was working as expected for me

**Review by akurinnoy — APPROVED** [review]
I approve this PR as is and waiting for unit tests in the following PR; all these changes should be covered by tests, otherwise, we're doomed to fall into this issue again and again.

**Review by akurinnoy — APPROVED** [review]

**Pull request merged**
